name: Sequencer-Build

on:
  push:
    paths-ignore:
      - 'documentation/*'
      - '**/*.html'
      - '**/*.md'
  pull_request:

env:
  SETUP_PATH: .ci-local
  APT: re2c
  CHOCO: re2c
  BREW: re2c

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    # Set environment variables from matrix parameters
    env:    
      CMP: ${{ matrix.cmp }}
      BCFG: ${{ matrix.configuration }}
      BASE: ${{ matrix.base }}
      CI_CROSS_TARGETS: ${{ matrix.cross }}
      EXTRA: ${{ matrix.extra }}
      TEST: ${{ matrix.test }}
      VV: "1"

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            name: "Ub-22 gcc base-7.0"

          - os: ubuntu-latest
            cmp: clang
            configuration: default
            base: "7.0"
            name: "Ub-22 clang base-7.0"

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "3.15"
            name: "Ub-22 gcc base-3.15"

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "3.14"
            name: "Ub-22 gcc base-3.14"

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            cross: "RTEMS-pc686-qemu@5"
            base: "7.0"
            name: "Ub-22 gcc + RT-5.1 pc686 base-7.0"

          - os: macos-latest
            cmp: clang
            configuration: default
            base: "7.0"
            name: "Mac clang base-7.0"

          - os: windows-2019
            cmp: vs2019
            configuration: default
            base: "7.0"
            name: "Win2019 MSC19 base-7.0"

          - os: windows-2019
            cmp: vs2019
            configuration: static
            base: "7.0"
            name: "Win2019 MSC19 static base-7.0"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: "apt-get install"
      run: |
        sudo apt-get update
        sudo apt-get -y install re2c gdb
      if: runner.os == 'Linux'
    - name: Automatic core dumper analysis
      uses: mdavidsaver/ci-core-dumper@master
    - name: Prepare and compile dependencies
      run: python .ci/cue.py prepare
    - name: Apply patches
      run: patch -p1 -i ./seq-2.2.9-base707-fix.patch
    - name: Build main module
      run: python .ci/cue.py -T 60M build
    - name: Run main module tests
      run: python -m ci_core_dumper exec python .ci/cue.py -T 15M test
    - name: Collect and show test results
      if: ${{ always() }}
      run: python .ci/cue.py -T 5M test-results
